[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
y = 5

[window]
opacity = 0.70
decorations = "buttonless"
blur = true

option_as_alt = "Both"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "c"
mods = "Alt"
chars = "\u001bc"

[[keyboard.bindings]]
key = "t"
mods = "Alt"
chars = "\u001bt"

[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u0017"
