# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](section_1_bg)\
$os\
[](bg:section_2_bg fg:section_1_bg)\
$directory\
[](fg:dir_bg bg:git_bg)\
($git_branch\
$git_status\
[](fg:git_bg bg:#212736))\
( $nodejs\
$rust\
$golang\
$php\
$c\
[](fg:#212736 bg:#1d2230))\
$time\
[ ](fg:#1d2230)\
\n$character"""

right_format = """$time"""

palette = 'theme'

[os]
disabled = false
style = "bg:section_1_bg fg:section_1_fg"
format = '[ $symbol ]($style)'
[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "bg:dir_bg fg:dir_fg"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "󰘍/"
home_symbol = "~"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = ""

[git_branch]
symbol = ""
style = "bg:git_bg"
format = '[[ $symbol $branch](fg:git_fg bg:git_bg)]($style)'

[git_status]
style = "bg:git_bg"
format = '[[($all_status$ahead_behind )](fg:git_fg bg:git_bg)]($style)'
ahead = " ⇡${count}"
behind = " ⇣${count}"
modified = " !${count}"
untracked = " ?${count}"
staged = " +${count}"
stashed = " \\$${count}"

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:time_bg"
format = '[[  $time ](fg:time_fg bg:time_bg)]($style)'

[palettes.theme]
bg = "#1f2335"
fg = "#a9b1d6"
section_1_fg = "#1f2335"
section_1_bg = "#a9b1d6"
section_2_fg = "#a9b1d6"
section_2_bg = "#7aa2f7"
os_fg = "#000000"
os_bg = "#a3aed2"
dir_fg = "#e3e5e5"
dir_bg = "#769ff0"
git_fg = "#769ff0"
git_bg = "#394260"
time_fg = "#a0a9cb"
time_bg = "#1d2230"
